### ISSUE TITLE
Document additional dependencies

### ISSUE THREAD

**Issue by radomirbosak** [M4rtinK/tsubame#3]
* python3-twitter

**Comment by M4rtinK** [comment]
Should be now properly bundled (including transitive dependencies of python-twitter) as Tsubame now runs properly on Sailfish OS which has a very limited amount of Python modules available from its repositories.

A note about bundling: All bundled Python modules are located in `core/bundle` folder, which is also added to path. This should make un-bundling rather straightforward - deleting the bundle folder and making sure system versions of the contained modules are installed.
