### ISSUE TITLE
Long tweets are sometimes truncated

### ISSUE THREAD

**Issue by M4rtinK** [M4rtinK/tsubame#86]
Possibly a problem with the python-twitter library or some knob that needs to be set in it ?

**Comment by M4rtinK** [comment]
Turns out this is due to retweets - we need to retrieve the original Tweet from the retweet or elkse the text is truncated.

**Comment by jkonecny12** [comment]
Just today I was thinking about that and trying to find out if this is happening only on retweets... :D

**Comment by M4rtinK** [comment]
This should be now fully handled as support for retweets and quoting has been added.

**Comment by jkonecny12** [comment]
Thanks!
